version: '3.5'
services:
  db:
    build: postgresql
    image: taskmanager_postgresql:1.1.8
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - taskmanager_ntwrk
  pgadmin:
    build: pgadmin
    image: taskmanager_pgadmin:1.0.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - taskmanager_ntwrk
  swagger-ui:
    build: swagger-ui
    image: taskmanager_swagger-ui:1.0.1
    ports:
      - "81:8080"
    networks:
      - taskmanager_ntwrk

  user-service:
    build: user-service
    image: taskmanager_user-service:1.1.3
    networks:
      - taskmanager_ntwrk
  audit-service:
    build: audit-service
    image: taskmanager_audit-service:1.1.1
    networks:
      - taskmanager_ntwrk
  notification-service:
    build: notification-service
    image: taskmanager_notification-service:1.0.6
    networks:
      - taskmanager_ntwrk
  task-service:
    build: task-service
    image: taskmanager_task-service:1.1.1
    networks:
      - taskmanager_ntwrk
  proxy:
    build: proxy
    image: taskmanager_proxy:1.0.20
    ports:
      - "80:80"
    networks:
      - taskmanager_ntwrk
  report-service:
    depends_on:
      - db
      - minio
    build: report-service
    image: taskmanager_report-service:1.0.0
    networks:
      - taskmanager_ntwrk
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/report_service?ApplicationName=Report_Service
      spring.datasource.username: root
      spring.datasource.password: root
      app.network.user_service.address: user-service:8080
      app.network.audit_service.address: audit-service:8080
      app.network.minio.host: minio:9000
  minio:
    image: bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    networks:
      - taskmanager_ntwrk
networks:
    taskmanager_ntwrk:
      name: taskmanager_ntwrk