spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/tm_audit?ApplicationName=tmAudit
    username: audit
    password: a7530305
    hikari:
      schema: app
      maximum-pool-size: 5
  cloud:
    openfeign:
      client:
        config:
          user-service:
            url: http://user-service:8080
jwt:
  secret: 0123456789
  issuer: Task Manager


