spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tmAudit?ApplicationName=tmAudit
    username: audit
    password: a7530305
    hikari:
      schema: app
server:
  port: 82

