spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tm_user?ApplicationName=user
    username: user
    password: uroot
    hikari:
      schema: app
server:
  port: 80
jwt:
  secret: 0123456789
  issuer: Task Manager
natification-service:
  url: http://localhost:81
  name: natification-service
audit-service:
  url: http://localhost:82
  name: audit-service