spring:
  cloud:
    openfeign:
      client:
        config:
          notification-service:
            url: http://notification-service:8080
          audit-service:
            url: http://audit-service:8080
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/tm_user?ApplicationName=user
    username: user
    password: uroot
    hikari:
      schema: app
      maximum-pool-size: 5
jwt:
  secret: 0123456789
  issuer: Task Manager
