spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tm_task?ApplicationName=task
    username: task
    password: taskmanager
    hikari:
      schema: app
server:
  port: 84
jwt:
  secret: 0123456789
  issuer: Task Manager
audit-service:
  url: http://localhost:82
  name: audit-service
natification-service:
  url: http://localhost:81
  name: natification-service